// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ6UYDeO8XiTJQzALnwBTcub0hrYaxiV4',
    appId: '1:46597263959:web:e61df00be9f3c11b474912',
    messagingSenderId: '46597263959',
    projectId: 'qalaatal-dhaman-team',
    authDomain: 'qalaatal-dhaman-team.firebaseapp.com',
    storageBucket: 'qalaatal-dhaman-team.firebasestorage.app',
    measurementId: 'G-SK85E68WJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpnntWdKsDl-TAtwPIjgujH3nQiy6lV1c',
    appId: '1:46597263959:android:9342ce3156616e40474912',
    messagingSenderId: '46597263959',
    projectId: 'qalaatal-dhaman-team',
    storageBucket: 'qalaatal-dhaman-team.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCntnqqnpfAch24emyLQuSKATgaQS0tJ9A',
    appId: '1:46597263959:ios:06b276efb308560e474912',
    messagingSenderId: '46597263959',
    projectId: 'qalaatal-dhaman-team',
    storageBucket: 'qalaatal-dhaman-team.firebasestorage.app',
    iosBundleId: 'com.qalaataldhaman.team',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCntnqqnpfAch24emyLQuSKATgaQS0tJ9A',
    appId: '1:46597263959:ios:06b276efb308560e474912',
    messagingSenderId: '46597263959',
    projectId: 'qalaatal-dhaman-team',
    storageBucket: 'qalaatal-dhaman-team.firebasestorage.app',
    iosBundleId: 'com.qalaataldhaman.team',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ6UYDeO8XiTJQzALnwBTcub0hrYaxiV4',
    appId: '1:46597263959:web:b6fd1150a0c530ef474912',
    messagingSenderId: '46597263959',
    projectId: 'qalaatal-dhaman-team',
    authDomain: 'qalaatal-dhaman-team.firebaseapp.com',
    storageBucket: 'qalaatal-dhaman-team.firebasestorage.app',
    measurementId: 'G-D7R2DV5Z1F',
  );
}
